[project]
authors = ["Nacef Guessaymi <nacefguess@hotmail.com>"]
channels = ["conda-forge"]
name = "env"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
polars = ">=1.22.0,<2"
black = ">=25.1.0,<26"
